export const CHANGE_DATE = 'CHANGE_DATE';
export const SET_LOADING = 'SET_LOADING';
export const SAVE_RESULT = 'SAVE_RESULT';
export const MARK_SELECT_VALUE = 'MARK_SELECT_VALUE';
export const UNMARK_SELECT_VALUE = 'UNMARK_SELECT_VALUE';
export const SET_PERIOD = 'SELECT_PERIOD';
export const SET_PERIOD_LENGTH = 'SET_PERIOD_LENGTH';
export const PREPARE_DATA = 'PREPARE_DATA';